paginas:
    name: Paginas
    singular_name: Pagina
    fields:
        title:
            type: text
            class: large
        heading:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        image:
            type: image
            upload: paginas
            extensions: [ jpg ]
        body:
            type: html
        template:
            type: templateselect
            filter: '*.twig'
    default_status: publish
    sort: -datepublish

nieuws:
    name: Nieuws
    singular_name: Artikel
    singular_slug: nieuws
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        header:
            type: image
            upload: nieuws
            extensions: [ jpg ]
        intro:
            type: html
            height: 300px
        body:
            type: html
            height: 300px
        auteur:
            type: text
    taxonomy: [ jaar ]
    listing_records: 8
    record_template: article.twig
    listing_template: news.twig
    default_status: publish
    sort: -datepublish

fotos:
    name: Fotos
    singular_name: Album
    singular_slug: fotos
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        albumthumb:
            type: image
            upload: fotos
            extensions: [ jpg ]
        albumfotos:
            type: imagelist
            upload: fotos
            extensions: [ jpg ]
    record_template: album.twig
    listing_template: photos.twig
    default_status: publish
    sort: -datepublish
    
kalender:
    name: Kalender
    singular_name: Tocht
    fields:
        title:
            type: text
        afstand:
            type: text
        opmerking:
            type: text
        coordinator:
            type: text
    viewless: true
    listing_template: calendar.twig
    default_status: publish
    sort: datepublish

# possible field types:
# text - varchar(256) - input type text.
# integer - integer - Input field for integer numbers.
# float - double - Input field for floating numbers, stored as 'Double'.
# geolocation - text (65kb) - Input field for geolocation. Enter an address, and the location is geocoded to latitude/longitude coordinates
# imagelist - text (65kb) - Input type for imagelists. Add multiple images with a description. Useful for image sliders, galleries, etcetera.
# image - varchar(256) - image select/upload widget, stored as filename.
# file - varchar(256) - file select/upload widget, stored as filename.
# filelist - text (65kb) - Input type for a list of files. Including a description.
# video - varchar(256) - Video embed widget, stored as filename.
# html - text (65kb) - wysiwyg element.
# textarea - varchar(32768) - Simple, plain < textarea > field.
# markdown - varchar(32768) - Simple, plain < textarea > field, which is parsed as Markdown text.
# datetime - datetime - date and time selector widget.
# date - datetime - date selector widget.
# select - varchar(256) - select with predefined values
# templateselect - varchar(256) - select with template filenames
# checkbox - integer - checkbox-field which is 1 (checked) or 0 (unchecked)


# number (deprecated) - input type decimal(18,9), useful for storing number that need to be sortable
