# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
  - label: Home
    path: homepage
  - label: Over ons
    path: /over-ons
  - label: Kalender
    path: /tochten
  - label: Nieuws
    path: /nieuws
  - label: Foto's
    path: /fotos
  - label: Contact
    link: /contact
