# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: http://docs.bolt.cm/taxonomies#taxonomies

jaar:
    name: Jaar
    slug: jaar
    singular_name: Jaar
    singular_slug: jaar
    behaves_like: categories
    multiple: false
    postfix: "Selecteer het jaar waarin het artikel is geschreven."
    options: [ 1999, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021 ]
